version: "3.7"

services:
  database:
    image: postgres:12-alpine
    container_name: database
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER_FILE=/run/secrets/dbuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/dbpassword
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
      - dataStore:/var/lib/postgresql/data
    ports:
      - 5432:5432
    privileged: true
    secrets:
      - dbuser
      - dbpassword

volumes:
  dataStore:

secrets:
  dbuser:
    file: ./.db_admin_name.txt
  dbpassword:
    file: ./.db_admin_pwd.txt
